---
deployment:
  tasks:
    - rm -rf /home/cp1592537p25/public_html/css
    - rm -rf /home/cp1592537p25/public_html/img
    - rm -rf /home/cp1592537p25/public_html/js
    - rm -f /home/cp1592537p25/public_html/.htaccess
    - rm -f /home/cp1592537p25/public_html/favicon.ico
    - rm -f /home/cp1592537p25/public_html/index.php
    - rm -f /home/cp1592537p25/public_html/index_production.php
    - rm -f /home/cp1592537p25/public_html/mix-manifest.json
    - rm -f /home/cp1592537p25/public_html/robots.txt
    - rm -f /home/cp1592537p25/public_html/web.config
    - cp -R /home/cp1592537p25/OCSC_repo/public/. /home/cp1592537p25/public_html/
    - rsync -au --delete "/home/cp1592537p25/OCSC_repo" "/home/cp1592537p25/OCSC_deployment"
